version: '3.6'

services:

  web:
    build: ./chat_server
    container_name: chat_server
    ports:
      - "9000:8000"
    depends_on:
      - db
    command: bash -c "
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "
    env_file: .env.chat_server
    restart: always

  db:
    image: postgres:12.0-alpine
    container_name: chat_server_data
    volumes:
      - ./dbdata/:/var/lib/postgresql/data/
    env_file: .env.chat_server

